### ISSUE TITLE
Allow xpkeeper.admin permission node to remove other player's XPKeeper signs

### ISSUE THREAD

**Issue by Rumsfield** [eccentricdevotion/XPKeeper#1]
Please implement users with the xpkeepr.admin permission node to be able to destroy other player's XPKeeper signs. The issue currently is as follows:

Prerequisites:
1. Set up a Minecraft Spigot 1.8.7 server with PermissionsEX, XPKeeper and Worldedit
2. Have a default player, with the xpkeeper.use permission node
3. Have another player as an Op.

Steps:
1. The default player creates an XPKeeper sign.
2. The Op types /xpkforceremove <default player name>
3. The Op removes the XPKeeper sign of the default player using Worldedit
4. The default player attempts to create a new XPKeeper sign, but cannot because XPKeeper says the player can only have one sign.

Suggested Resolution:
When the Op types /xpkforceremove <name>, prompt the Op to click the XPKeeper sign to be removed from the world (similar to how /xpkremove works).

**Comment by eccentricdevotion** [comment]
Done https://github.com/eccentricdevotion/XPKeeper/commit/aa80780e511ffdddb349c29b6a6e804f799b5fab
