### ISSUE TITLE
XP: -1 shown when trying to use sign

### ISSUE THREAD

**Issue by sawarahh** [eccentricdevotion/XPKeeper#11]
https://github.com/eccentricdevotion/XPKeeper/assets/25620007/1cfdd6f2-53ed-41ee-9895-96850bac024a

Just updated from 1.20.2 to 1.20.4 on Paper. Using XPKeeper version 1.9.0. I also changed the world name 'world' to '1204.s' to prepare for Multiverse.

The attached video is what happens now. You cannot right click to withdraw. When you left click an empty sign, your XP deposits. If you left click a sign with XP in it, it shows 0 levels and -1 XP.

**Comment by sawarahh** [comment]
Removing the sign entirely and starting over works, just not my favorite solution with a lot of players on my server.

**Comment by eccentricdevotion** [comment]
Not sure what you expect from a location based sign - you have effectively changed the location to another world, I'm not surprised you are having issues...
Plus naming worlds with a `.` in them is very bad practice for Bukkit servers - any plugin that stores world names in yml files will generally have problems.

**Comment by eccentricdevotion** [comment]
Have you tried the `/xpkupdate` command? Might work...

**Comment by eccentricdevotion** [comment]
I've added a `world` argument to the `/xpkupdate` command so players can update their signs for a world name change.

`/xpkupdate [old world name]`

in your case:

`/xpkupdate world`

They should then right-click the sign.
__They should do this *before* interacting with the sign in any other way!__

Get the update here: http://tardisjenkins.duckdns.org:8080/job/XPKeeper/

**Comment by sawarahh** [comment]
I really appreciate the assistance and update despite this being such a dumb move on my part and entirely my own doing. Thanks. :)
