### ISSUE TITLE
xpkcolor and xpkforce have no permissions :-/

### ISSUE THREAD

**Issue by natsimhan** [eccentricdevotion/XPKeeper#3]
Hi,

All is in the title :) I use the latest version available.
Without any permission, all users can launch /xpkcolor or /xpkforce .... and it's little inapriopriate, isn't it ? 

Thank's for this plugin I'm using on my server (~50 actives users) !

**Comment by eccentricdevotion** [comment]
xpkforce = `xpkeeper.force` - only players with this permission can force remove _other players'_ records, they can always force remove their own record (and lose their own data/exp)

There were some issues with how this was working, but they should be fixed now.

Have added permissions check for /xpkcolor

**Comment by eccentricdevotion** [comment]
New build (1.4.7) uploaded to BukkitDev

or get it here: http://tardisjenkins.duckdns.org:8080/job/XPKeeper/lastSuccessfulBuild/me.eccentric_nz.plugins.xpkeeper$XPKeeper/
