### ISSUE TITLE
Allow to place multiple XPKeeper signs in a single world

### ISSUE THREAD

**Issue by Programie** [eccentricdevotion/XPKeeper#5]
Currently, this plugin only allows one XPKeeper sign per player per world. I.e. a player can't place another XPKeeper sign if he/she already has one in the same world.

But it would be really useful to allow placing multiple XPKeeper signs for a single player in a single world.

The database entry is retrieved using the world name and player UUID. Maybe giving the XPKeeper sign an ID stored as meta data of the sign block would allow to place multiple signs for a single player. In that way, you would simply store an incremental ID of the database entry in the sign block meta data.

**Comment by eccentricdevotion** [comment]
Build available on the TARDIS Jenkins server: http://tardisjenkins.duckdns.org:8080/job/XPKeeper/
