### ISSUE TITLE
Build #39 doesn't enable

### ISSUE THREAD

**Issue by baailey** [eccentricdevotion/XPKeeper#6]
16.07 02:08:22 [Server] ERROR Error occurred while enabling XPKeeper v1.8 (Is it up to date?)
16.07 02:08:22 [Server] INFO java.lang.NoClassDefFoundError: me/eccentric_nz/xpkeeper/XPKConfig
16.07 02:08:22 [Server] INFO at me.eccentric_nz.xpkeeper.XPKeeper.onEnable(XPKeeper.java:40) ~[?:?]
16.07 02:08:22 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
16.07 02:08:22 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.eccentric_nz.xpkeeper.XPKConfig
16.07 02:08:22 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
16.07 02:08:22 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
16.07 02:08:22 [Server] INFO ... 11 more

Version: git-Tuinity-"2310a94" (MC: 1.17.1)

**Comment by eccentricdevotion** [comment]
Looks like Jenkins builds are doing something weird, looking into it

**Comment by eccentricdevotion** [comment]
Try build #43
