### ISSUE TITLE
Minecraft's new sign edit feature can be used to edit XPKeeper signs

### ISSUE THREAD

**Issue by baailey** [eccentricdevotion/XPKeeper#9]
When attempting to withdraw XP from a XPKeeper sign, it triggers the sign edit feature. If you could figure out a way to block the sign edit from happening, that'd be great.

**Comment by eccentricdevotion** [comment]
http://tardisjenkins.duckdns.org:8080/job/XPKeeper/

**Comment by baailey** [comment]
That works, thanks. However, previously when making an XPKeeper sign you could just write [XPKeeper] on the top line and it'd fill out the whole template (name, level, xp). But now, when you write it out it makes it, but doesn't update the sign to add the rest of the info until the player clicks to deposit/withdraw XP. Is this a new bug, or an intentional new design?

https://youtu.be/P8bx9QCjTb0

**Comment by eccentricdevotion** [comment]
Weird, was working when I tested it initially, maybe a Spigot/Paper update changed something.
Now working again after delaying the code execution that writes the sign by 2 ticks.
Build 52, same link as above

**Comment by baailey** [comment]
All good now, thanks for the quick fixes!
